import { Metadata } from "next";
//static metadata
// export const metadata = {
//   title: "Web",
//   description: "Generated by Next.js",
// };
//dynamic metadata
export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "NextJs ",
    template: "%s | nextjs",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "lightblue", padding: "0.2rem" }}>
          <p>Header</p>
        </header>
        {children}
        <footer style={{ backgroundColor: "lightgray", padding: "0.2rem" }}>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
